trigger:
  branches:
    include:
      - main  # or your desired branch

pool:
  vmImage: 'ubuntu-latest'  # Use 'windows-latest' if required

variables:
  MAVEN_OPTS: "-Xmx1024m"

steps:

# Step 1: Checkout your code
- checkout: self

# Step 2: Set up JDK
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'                       # or whatever version you need
    jdkArchitectureOption: 'x64'            # REQUIRED input
    jdkSourceOption: 'PreInstalled'  

# Step 3: Cache Maven dependencies
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
    path: ~/.m2/repository

# Step 4: Run Maven build and tests
- script: |
    mvn clean test
  displayName: 'Run Tests with Maven'

# Step 5: Publish TestNG results (JUnit format)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testng-results.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'TestNG Results'

# Step 6: Publish Extent Report as artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'test-output/ExtentReports'  # Adjust path if needed
    ArtifactName: 'ExtentReport'
    publishLocation: 'Container'
