trigger:
  branches:
    include:
      - main
      - pagefactory

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx1024m"

steps:

- checkout: self

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'                       # or whatever version you need
    jdkArchitectureOption: 'x64'            # REQUIRED input
    jdkSourceOption: 'PreInstalled' 
    

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
    path: ~/.m2/repository

- script: |
    mvn clean test --batch-mode -e -X
  displayName: 'Run Tests with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'TestNG Results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'test-output/ExtentReports'
    ArtifactName: 'ExtentReport'
    publishLocation: 'Container'
